### ISSUE TITLE
application to OpenBazaar search?

### ISSUE THREAD

**Issue by wds4** [hoschiCZ/ipfsearch-webapp#1]
Hey Ondřej,
@BazaarDog just posted a link to your ipfsearch project on the # 3rd-party-search channel of the OpenBazaar slack. Have you followed OpenBazaar at all? You may know that OpenBazaar data is stored on a fork of ipfs, and a big question going forward is how to do searches for listings. Head on over there if you're interested! btw I'm @drDave on slack

**Comment by ondrejsojka** [comment]
Hello.
I have applied to join the slack at https://www.openbazaar.org/slack/ . I am definitely seeing a potential use-case for this and OpenBazaar.
